package com.letta.mobile.feature.editagent

internal data class EditAgentContentCallbacks(
    val onNameChange: (String) -> Unit,
    val onDescriptionChange: (String) -> Unit,
    val onModelChange: (String) -> Unit,
    val onEmbeddingChange: (String) -> Unit,
    val onLoadModels: () -> Unit,
    val onBlockValueChange: (String, String) -> Unit,
    val onBlockDescriptionChange: (String, String) -> Unit,
    val onBlockLimitChange: (String, Int?) -> Unit,
    val onAddBlock: (String, String, String, Int?) -> Unit,
    val onAttachExistingBlock: (String) -> Unit,
    val onAttachExistingBlocks: (List<String>) -> Unit,
    val onDeleteBlock: (String) -> Unit,
    val onAddTag: (String) -> Unit,
    val onRemoveTag: (String) -> Unit,
    val onAttachTool: (String) -> Unit,
    val onAttachTools: (List<String>) -> Unit,
    val onDetachTool: (String) -> Unit,
    val onToolRulesJsonChange: (String) -> Unit,
    val onAddAgentSecret: () -> Unit,
    val onAgentSecretKeyChange: (Int, String) -> Unit,
    val onAgentSecretValueChange: (Int, String) -> Unit,
    val onRemoveAgentSecret: (Int) -> Unit,
    val onAddToolEnvironmentVariable: () -> Unit,
    val onToolEnvironmentVariableKeyChange: (Int, String) -> Unit,
    val onToolEnvironmentVariableValueChange: (Int, String) -> Unit,
    val onRemoveToolEnvironmentVariable: (Int) -> Unit,
    val onSystemPromptChange: (String) -> Unit,
    val onProviderTypeChange: (String) -> Unit,
    val onTemperatureChange: (Float) -> Unit,
    val onMaxOutputTokensChange: (Int) -> Unit,
    val onParallelToolCallsChange: (Boolean) -> Unit,
    val onModelProviderNameChange: (String) -> Unit,
    val onModelProviderCategoryChange: (String) -> Unit,
    val onModelEnableReasonerChange: (Boolean) -> Unit,
    val onModelReasoningEffortChange: (String) -> Unit,
    val onModelMaxReasoningTokensChange: (String) -> Unit,
    val onModelReasoningJsonChange: (String) -> Unit,
    val onModelFrequencyPenaltyChange: (String) -> Unit,
    val onModelVerbosityChange: (String) -> Unit,
    val onModelStrictToolCallingChange: (Boolean) -> Unit,
    val onModelResponseFormatJsonChange: (String) -> Unit,
    val onModelResponseSchemaJsonChange: (String) -> Unit,
    val onModelThinkingConfigJsonChange: (String) -> Unit,
    val onModelPutInnerThoughtsInKwargsChange: (Boolean) -> Unit,
    val onModelToolCallParserChange: (String) -> Unit,
    val onModelAnthropicEffortChange: (String) -> Unit,
    val onContextWindowChange: (Int) -> Unit,
    val onEnableSleeptimeChange: (Boolean) -> Unit,
    val onSummarizationPromptChange: (String) -> Unit,
    val onCompactionClipCharsChange: (Int) -> Unit,
    val onSlidingWindowPercentageChange: (Float) -> Unit,
    val onPromptAcknowledgementChange: (Boolean) -> Unit,
    val onCompactionModeChange: (String) -> Unit,
    val onCompactionModelChange: (String) -> Unit,
    val onCompactionModelSettingsJsonChange: (String) -> Unit,
    val onResetMessages: () -> Unit,
    val onDeleteAgent: () -> Unit,
)

internal fun EditAgentViewModel.contentCallbacks(
    onResetMessages: () -> Unit,
    onDeleteAgent: () -> Unit,
): EditAgentContentCallbacks = EditAgentContentCallbacks(
    onNameChange = ::updateName,
    onDescriptionChange = ::updateDescription,
    onModelChange = ::updateModel,
    onEmbeddingChange = ::updateEmbedding,
    onLoadModels = ::loadModels,
    onBlockValueChange = ::updateBlockValue,
    onBlockDescriptionChange = ::updateBlockDescription,
    onBlockLimitChange = ::updateBlockLimit,
    onAddBlock = ::addBlock,
    onAttachExistingBlock = ::attachExistingBlock,
    onAttachExistingBlocks = ::attachExistingBlocks,
    onDeleteBlock = ::deleteBlock,
    onAddTag = ::addTag,
    onRemoveTag = ::removeTag,
    onAttachTool = ::attachTool,
    onAttachTools = ::attachTools,
    onDetachTool = ::detachTool,
    onToolRulesJsonChange = ::updateToolRulesJson,
    onAddAgentSecret = ::addAgentSecret,
    onAgentSecretKeyChange = ::updateAgentSecretKey,
    onAgentSecretValueChange = ::updateAgentSecretValue,
    onRemoveAgentSecret = ::removeAgentSecret,
    onAddToolEnvironmentVariable = ::addToolEnvironmentVariable,
    onToolEnvironmentVariableKeyChange = ::updateToolEnvironmentVariableKey,
    onToolEnvironmentVariableValueChange = ::updateToolEnvironmentVariableValue,
    onRemoveToolEnvironmentVariable = ::removeToolEnvironmentVariable,
    onSystemPromptChange = ::updateSystemPrompt,
    onProviderTypeChange = ::updateProviderType,
    onTemperatureChange = ::updateTemperature,
    onMaxOutputTokensChange = ::updateMaxOutputTokens,
    onParallelToolCallsChange = ::updateParallelToolCalls,
    onModelProviderNameChange = ::updateModelProviderName,
    onModelProviderCategoryChange = ::updateModelProviderCategory,
    onModelEnableReasonerChange = ::updateModelEnableReasoner,
    onModelReasoningEffortChange = ::updateModelReasoningEffort,
    onModelMaxReasoningTokensChange = ::updateModelMaxReasoningTokens,
    onModelReasoningJsonChange = ::updateModelReasoningJson,
    onModelFrequencyPenaltyChange = ::updateModelFrequencyPenalty,
    onModelVerbosityChange = ::updateModelVerbosity,
    onModelStrictToolCallingChange = ::updateModelStrictToolCalling,
    onModelResponseFormatJsonChange = ::updateModelResponseFormatJson,
    onModelResponseSchemaJsonChange = ::updateModelResponseSchemaJson,
    onModelThinkingConfigJsonChange = ::updateModelThinkingConfigJson,
    onModelPutInnerThoughtsInKwargsChange = ::updateModelPutInnerThoughtsInKwargs,
    onModelToolCallParserChange = ::updateModelToolCallParser,
    onModelAnthropicEffortChange = ::updateModelAnthropicEffort,
    onContextWindowChange = ::updateContextWindow,
    onEnableSleeptimeChange = ::updateEnableSleeptime,
    onSummarizationPromptChange = ::updateSummarizationPrompt,
    onCompactionClipCharsChange = ::updateCompactionClipChars,
    onSlidingWindowPercentageChange = ::updateSlidingWindowPercentage,
    onPromptAcknowledgementChange = ::updatePromptAcknowledgement,
    onCompactionModeChange = ::updateCompactionMode,
    onCompactionModelChange = ::updateCompactionModel,
    onCompactionModelSettingsJsonChange = ::updateCompactionModelSettingsJson,
    onResetMessages = onResetMessages,
    onDeleteAgent = onDeleteAgent,
)
