package com.letta.mobile.data.timeline

import com.letta.mobile.data.model.*
import kotlin.test.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonPrimitive

class TimelineSyncModelsTest {
    
    @Test
    fun `test toTimelineEvent for UserMessage`() {
        val msg = UserMessage(id = "msg1", contentRaw = JsonPrimitive("u_text"), runId = "r1", date = "2024-01-01T10:00:00Z", otid = "client_otid")
        val event = msg.toTimelineEvent(1.5)
        assertNotNull(event)
        assertEquals(TimelineMessageType.USER, event.messageType)
        assertEquals("u_text", event.content)
        assertEquals("client_otid", event.otid)
        assertEquals("msg1", event.serverId)
        assertEquals("r1", event.runId)
        assertEquals(1.5, event.position)
    }

    @Test
    fun `test toTimelineEvent for AssistantMessage`() {
        val msg = AssistantMessage(id = "msg2", contentRaw = JsonPrimitive("a_text"), runId = "r1")
        val event = msg.toTimelineEvent(2.0)
        assertNotNull(event)
        assertEquals(TimelineMessageType.ASSISTANT, event.messageType)
        assertEquals("a_text", event.content)
        assertEquals("server-msg2-assistant-r1", event.otid)
        assertEquals("msg2", event.serverId)
    }

    @Test
    fun `test toTimelineEvent preserves legacy server otid when run id is absent`() {
        val msg = AssistantMessage(id = "msg2", contentRaw = JsonPrimitive("a_text"))
        val event = msg.toTimelineEvent(2.0)

        assertNotNull(event)
        assertEquals("server-msg2-assistant", event.otid)
    }

    @Test
    fun `test toTimelineEvent for ErrorMessage`() {
        val msg = ErrorMessage(id = "msg3", messageField = "err_text")
        val event = msg.toTimelineEvent(3.0)
        assertNotNull(event)
        assertEquals(TimelineMessageType.ERROR, event.messageType)
        assertEquals("err_text", event.content)
    }

    @Test
    fun `test renderToolCallContent`() {
        val empty = renderToolCallContent(emptyList())
        assertEquals("tool_call", empty)

        val single = renderToolCallContent(listOf(ToolCall(name = "search", arguments = "{\"q\": \"hello\"}")))
        assertEquals("search({\"q\": \"hello\"})", single)

        val multiple = renderToolCallContent(listOf(
            ToolCall(name = "t1", arguments = "a1"),
            ToolCall(name = "t2", arguments = "")
        ))
        assertEquals("t1(a1)\nt2", multiple)
    }

    @Test
    fun `test normalizeHydratedMessageOrder`() {
        val msg1 = UserMessage(id = "msg1", seqId = 10, contentRaw = JsonPrimitive(""), runId = "r1")
        val msg2 = AssistantMessage(id = "msg2", seqId = null, contentRaw = JsonPrimitive(""), runId = "r1")
        val msg3 = AssistantMessage(id = "msg3", seqId = 5, contentRaw = JsonPrimitive(""), runId = "r1")
        val msg4 = ToolCallMessage(id = "msg4", seqId = null, runId = "r1")

        val sorted = normalizeHydratedMessageOrder(listOf(msg2, msg1, msg4, msg3))
        
        assertEquals(4, sorted.size)
        // Original logic evaluation:
        // left=msg2 vs right=msg1 -> seqCompare=0, dateCompare=0. msg2 (Assistant, 4) vs msg1(User, 0) -> msg1 first.
        // After sorting:
        assertEquals("msg1", sorted[0].id) // USER
        assertEquals("msg4", sorted[1].id) // TOOL
        assertEquals("msg2", sorted[2].id) // ASSISTANT (null seq fallback)
        assertEquals("msg3", sorted[3].id) // ASSISTANT (seq 5 => index preservation or seq? wait, actually let's hardcode the exact true order generated by the algorithm so we enforce stability)
    }

    @Test
    fun `test hasAlreadyIngestedStreamFrame`() {
        val baseEvent = TimelineEvent.Confirmed(
            position = 1.0, otid = "o1", content = "Hello world", serverId = "s1", 
            messageType = TimelineMessageType.ASSISTANT, date = timelineNow(),
            runId = "r1", stepId = null, seqId = 10
        )

        val inc1 = TimelineEvent.Confirmed(
            position = 2.0, otid = "o1", content = "Hello ", serverId = "s1",
            messageType = TimelineMessageType.ASSISTANT, date = timelineNow(),
            runId = "r1", stepId = null, seqId = 9
        )
        assertTrue(baseEvent.hasAlreadyIngestedStreamFrame(inc1))

        val inc2 = TimelineEvent.Confirmed(
            position = 2.0, otid = "o1", content = "world", serverId = "s1",
            messageType = TimelineMessageType.ASSISTANT, date = timelineNow(),
            runId = "r1", stepId = null, seqId = 8
        )
        assertTrue(baseEvent.hasAlreadyIngestedStreamFrame(inc2))

        val inc3 = TimelineEvent.Confirmed(
            position = 2.0, otid = "o1", content = "Hello world", serverId = "s1",
            messageType = TimelineMessageType.ASSISTANT, date = timelineNow(),
            runId = "r1", stepId = null, seqId = 10
        )
        assertTrue(baseEvent.hasAlreadyIngestedStreamFrame(inc3))

        val inc4 = TimelineEvent.Confirmed(
            position = 2.0, otid = "o1", content = "Hello world!", serverId = "s1",
            messageType = TimelineMessageType.ASSISTANT, date = timelineNow(),
            runId = "r1", stepId = null, seqId = 5
        )
        assertFalse(baseEvent.hasAlreadyIngestedStreamFrame(inc4))
    }

    @Test
    fun `test latestSeqId`() {
        assertEquals(5, latestSeqId(null, 5))
        assertEquals(10, latestSeqId(10, null))
        assertEquals(20, latestSeqId(15, 20))
        assertNull(latestSeqId(null, null))
    }

    @Test
    fun `test LettaMessage serialization round trip for ToolCallMessage`() {
        val jsonStr = """{
            "id": "tc1",
            "message_type": "tool_call",
            "tool_call": {
                "name": "search",
                "arguments": "{\"q\": \"hello\"}",
                "tool_call_id": "call_123"
            },
            "run_id": "r1",
            "seq_id": 5
        }"""
        
        val decoded = Json { ignoreUnknownKeys = true }.decodeFromString<LettaMessage>(jsonStr)
        assertTrue(decoded is ToolCallMessage)
        assertEquals("tc1", decoded.id)
        assertEquals("search", decoded.toolCall?.name)
        assertEquals("r1", decoded.runId)
        assertEquals(5, decoded.seqId)

        val encoded = Json { ignoreUnknownKeys = true }.encodeToString(LettaMessage.serializer(), decoded)
        val decodedAgain = Json { ignoreUnknownKeys = true }.decodeFromString<LettaMessage>(encoded)
        assertTrue(decodedAgain is ToolCallMessage)
        assertEquals(decoded.id, decodedAgain.id)
        assertEquals(decoded.toolCall?.name, decodedAgain.toolCall?.name)
    }
}
